name: Build Dev
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Latest Node
        uses: actions/setup-node@v2.4.0
      - name: Install Denpendencies
        run: npm install -d
      - name: Build
        run: npm run packageaddon
      - name: Upload to Actions
        uses: actions/upload-artifact@v1
        with:
          name: Addon_Build
          path: out/packaged/